certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf6gAwIBAgIRAOoTY+sC2MB9VKeD6u8SvaowCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNzA5MDg1NDAwWhcNMzAwNzA3MDg1

        NDAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABAsfpaOebDffVvPs717lYmUKKSkx7HrAh2YsQe+eCBXKyTD1fJOgHSXr

        FZjQbjifXDALkUkh7qg2/6W+mQmlVbqjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQggmWsezTEi0jkFYcorGB2nf0wr5rxS/dIJ3difWNJW44wCgYIKoZIzj0E

        AwIDSAAwRQIhANTrXmTT4iOSdxdmch65S/ZSfRQ/Njd8tUe2UmnszV8XAiAOcBxc

        L4zE5PQXlcc0MSKe3y9j36/fB3f96U8HgLt5UQ==

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf6gAwIBAgIRAOoTY+sC2MB9VKeD6u8SvaowCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNzA5MDg1NDAwWhcNMzAwNzA3MDg1

        NDAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABAsfpaOebDffVvPs717lYmUKKSkx7HrAh2YsQe+eCBXKyTD1fJOgHSXr

        FZjQbjifXDALkUkh7qg2/6W+mQmlVbqjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQggmWsezTEi0jkFYcorGB2nf0wr5rxS/dIJ3difWNJW44wCgYIKoZIzj0E

        AwIDSAAwRQIhANTrXmTT4iOSdxdmch65S/ZSfRQ/Njd8tUe2UmnszV8XAiAOcBxc

        L4zE5PQXlcc0MSKe3y9j36/fB3f96U8HgLt5UQ==

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
