certificateAuthorities:
  ca.org2.example.com:
    caName: ca.org2.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWTCCAf6gAwIBAgIRAP6xwOyRJS2g99h0H9+cH4IwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjAwNzExMDkxNTAwWhcNMzAwNzA5MDkx

        NTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABK/FzURAIue6nKtZZFJrWJWWeYDUgytCbpaBR7dzrsVH3ksZ1uu2ECTv

        TMF0xwxDaOUcCvlDN3bmy3ZFrG5Yn5mjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgJl72GdS7SVWFDPg/eXpXuARSYfIZSo/fbEoZzDpKr8AwCgYIKoZIzj0E

        AwIDSQAwRgIhAIChLBb31xQJmbsSfDn52jQIa+teKZZKdueP/q7RgF7/AiEA1GLG

        3ua1a2Fnsnrux9gMZYnDgu96FAG3YYzwHM91Zp4=

        -----END CERTIFICATE-----

        '}
    url: https://localhost:8054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org2
name: first-network-org2
organizations:
  Org2:
    certificateAuthorities: [ca.org2.example.com]
    mspid: Org2MSP
    peers: [peer0.org2.example.com]
peers:
  peer0.org2.example.com:
    grpcOptions: {hostnameOverride: peer0.org2.example.com, ssl-target-name-override: peer0.org2.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWTCCAf6gAwIBAgIRAP6xwOyRJS2g99h0H9+cH4IwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzIuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzIuZXhhbXBsZS5jb20wHhcNMjAwNzExMDkxNTAwWhcNMzAwNzA5MDkx

        NTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMi5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABK/FzURAIue6nKtZZFJrWJWWeYDUgytCbpaBR7dzrsVH3ksZ1uu2ECTv

        TMF0xwxDaOUcCvlDN3bmy3ZFrG5Yn5mjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgJl72GdS7SVWFDPg/eXpXuARSYfIZSo/fbEoZzDpKr8AwCgYIKoZIzj0E

        AwIDSQAwRgIhAIChLBb31xQJmbsSfDn52jQIa+teKZZKdueP/q7RgF7/AiEA1GLG

        3ua1a2Fnsnrux9gMZYnDgu96FAG3YYzwHM91Zp4=

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:8051
version: 1.0.0
