certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVjCCAf2gAwIBAgIQYYlMUcwBQ3i/0tcAltQBOzAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA2MjUwOTAyMDBaFw0zMDA2MjMwOTAy

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEe8VNQry6e8QpfT8tQiWH0csNXYEkEJ7dmskRie2KLaUlZZyi7AVG1KdX

        pgzuRCgRDo2uwycRY7C912XzoTNk1aNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCANIE5QogSEPo3mKuZFbu56aepu2TIq7A2e/PUDBfjMvzAKBggqhkjOPQQD

        AgNHADBEAiA3NtfNGyFP673Ousqg8HEZnGpgMsPKDZ/c8sRneSu8mAIgLnTmApEA

        zdddExkg1J6alxwJXkcBEx7NkZ/jbY0lPFo=

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVjCCAf2gAwIBAgIQYYlMUcwBQ3i/0tcAltQBOzAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA2MjUwOTAyMDBaFw0zMDA2MjMwOTAy

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEe8VNQry6e8QpfT8tQiWH0csNXYEkEJ7dmskRie2KLaUlZZyi7AVG1KdX

        pgzuRCgRDo2uwycRY7C912XzoTNk1aNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCANIE5QogSEPo3mKuZFbu56aepu2TIq7A2e/PUDBfjMvzAKBggqhkjOPQQD

        AgNHADBEAiA3NtfNGyFP673Ousqg8HEZnGpgMsPKDZ/c8sRneSu8mAIgLnTmApEA

        zdddExkg1J6alxwJXkcBEx7NkZ/jbY0lPFo=

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
