certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVzCCAf2gAwIBAgIQVrKrfdYNOpsujtyAjz3uJjAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA3MDkxNTI5MDBaFw0zMDA3MDcxNTI5

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEsDDPWECyP/SebMgq8GTcv1iQezsjABOtFskU9fblPe5a0LrMiJp5ghrV

        onATia6OZR0fC1x9fBVCtgnfKAgh1aNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCANxFEkyPC3StCrq6Iqsz65DWLT5A4uWB2AC3rM18y/3DAKBggqhkjOPQQD

        AgNIADBFAiAYyuDcaLRYVyQAIuUYU/D1gBoFAqgMmQD+jHQfoSuDZwIhAInu7fli

        5tjvf0WxV7TnF4i+KmJOdxy6QJOYAk1899f4

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVzCCAf2gAwIBAgIQVrKrfdYNOpsujtyAjz3uJjAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA3MDkxNTI5MDBaFw0zMDA3MDcxNTI5

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEsDDPWECyP/SebMgq8GTcv1iQezsjABOtFskU9fblPe5a0LrMiJp5ghrV

        onATia6OZR0fC1x9fBVCtgnfKAgh1aNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCANxFEkyPC3StCrq6Iqsz65DWLT5A4uWB2AC3rM18y/3DAKBggqhkjOPQQD

        AgNIADBFAiAYyuDcaLRYVyQAIuUYU/D1gBoFAqgMmQD+jHQfoSuDZwIhAInu7fli

        5tjvf0WxV7TnF4i+KmJOdxy6QJOYAk1899f4

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
