certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWTCCAf6gAwIBAgIRAPVjKXpC8fT6JHSKofKaGcgwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNzExMTI1MTAwWhcNMzAwNzA5MTI1

        MTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABKryIsWN8TEuZAVzIgZBw83dwDtdAdIUUXJ/e7qroh+DMBaKPuDkih2B

        EpHfZdFKfqxWPTR5WLIjJLY1QZOBIOOjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQg4BoOYvI+Y7SaKbF9JN8zKmGDB6p65vFrhio8dv4dxk0wCgYIKoZIzj0E

        AwIDSQAwRgIhAN9XF1DqzJp+t4aJFEyo3PAM569QtDHswYhxM7qoq01tAiEAoPE7

        k/pWHHcYq1b7+3c35CLtrL31ajx60F8plFdDavk=

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWTCCAf6gAwIBAgIRAPVjKXpC8fT6JHSKofKaGcgwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNzExMTI1MTAwWhcNMzAwNzA5MTI1

        MTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABKryIsWN8TEuZAVzIgZBw83dwDtdAdIUUXJ/e7qroh+DMBaKPuDkih2B

        EpHfZdFKfqxWPTR5WLIjJLY1QZOBIOOjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQg4BoOYvI+Y7SaKbF9JN8zKmGDB6p65vFrhio8dv4dxk0wCgYIKoZIzj0E

        AwIDSQAwRgIhAN9XF1DqzJp+t4aJFEyo3PAM569QtDHswYhxM7qoq01tAiEAoPE7

        k/pWHHcYq1b7+3c35CLtrL31ajx60F8plFdDavk=

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
