---
name: first-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    - peer1.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAKEmRNZ3r3//QNXg++TyPfMwCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
        c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjAwNDEyMDQwNTAwWhcNMzAwNDEwMDQw
        NTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G
        A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABHQYh1wVdCFbeve1oNjEwJqPjBxATrFxVa6475KvmgfLD7zcGSh3jWVr
        lfjRw53SwANcI7TUELtyUtF9UKVLv/yjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgdU6lUUpwLa/JJrpK+2HQtd6xCQs0DbaJpZQrLR381M0wCgYIKoZIzj0E
        AwIDSAAwRQIgVP4JQ0N3g++o0j6b4BWfe4YG/mFxmsPXD7bS0+wm4gUCIQCIo5s+
        Md6G3wcPMcU1jsfB7dSyS3M28yNpoPSAYwrQPQ==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
  peer1.org1.example.com:
    url: grpcs://localhost:8051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAKEmRNZ3r3//QNXg++TyPfMwCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
        c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjAwNDEyMDQwNTAwWhcNMzAwNDEwMDQw
        NTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G
        A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABHQYh1wVdCFbeve1oNjEwJqPjBxATrFxVa6475KvmgfLD7zcGSh3jWVr
        lfjRw53SwANcI7TUELtyUtF9UKVLv/yjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgdU6lUUpwLa/JJrpK+2HQtd6xCQs0DbaJpZQrLR381M0wCgYIKoZIzj0E
        AwIDSAAwRQIgVP4JQ0N3g++o0j6b4BWfe4YG/mFxmsPXD7bS0+wm4gUCIQCIo5s+
        Md6G3wcPMcU1jsfB7dSyS3M28yNpoPSAYwrQPQ==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      hostnameOverride: peer1.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICUTCCAfegAwIBAgIQDtICMKwud1RxfbE4kop1EzAKBggqhkjOPQQDAjBzMQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
        b3JnMS5leGFtcGxlLmNvbTAeFw0yMDA0MTIwNDA1MDBaFw0zMDA0MTAwNDA1MDBa
        MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
        YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMRwwGgYDVQQD
        ExNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
        KCng0b9Rmb3HYpTzlzVOUrc30j+GEgHjYCvgye4lwmP45Mfpwpo/+CFxFH/fQcSN
        U1RY82etq5NmnFGh2nYrvaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
        CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCBo
        uiwGJHQV+7F4KBlc2fC3XmMtWIPgEaQKLQRAL1WXCTAKBggqhkjOPQQDAgNIADBF
        AiAWiR0IYA5YoWtNNMl49NMk808h13lEMJUC2n5lB+E6AAIhAJ1XZDI8sIRvfPQ/
        L6rErNkRgUuxY8aJfqlDZWdWc3Kd
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
