certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf2gAwIBAgIQMtzdd3WTwiEWcxG+ILEBmDAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA3MDkxMjI2MDBaFw0zMDA3MDcxMjI2

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEFQe1r+LM+nwVCrEGN3MKrSwPo8149KBCKY/2F+bVKrPAur4DfiDz4but

        VPa+j4BpKPQ5DArOdRqo1e1D1MOmt6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCC0TDAPGGnXDkQuSMdC0H2U+vLQP6IXeI0DQLn88HUQfzAKBggqhkjOPQQD

        AgNJADBGAiEA+tZrhkGmwzXjsiv3uZypWNL2Ec3fKgTsGId2JnuoOMECIQCDo6Af

        D+YVc1FjtEmLD3CCGUU+tOSolZVymvwc2dqr+Q==

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf2gAwIBAgIQMtzdd3WTwiEWcxG+ILEBmDAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA3MDkxMjI2MDBaFw0zMDA3MDcxMjI2

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEFQe1r+LM+nwVCrEGN3MKrSwPo8149KBCKY/2F+bVKrPAur4DfiDz4but

        VPa+j4BpKPQ5DArOdRqo1e1D1MOmt6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCC0TDAPGGnXDkQuSMdC0H2U+vLQP6IXeI0DQLn88HUQfzAKBggqhkjOPQQD

        AgNJADBGAiEA+tZrhkGmwzXjsiv3uZypWNL2Ec3fKgTsGId2JnuoOMECIQCDo6Af

        D+YVc1FjtEmLD3CCGUU+tOSolZVymvwc2dqr+Q==

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
