---
name: first-network-org2
version: 1.0.0
client:
  organization: Org2
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org2:
    mspid: Org2MSP
    peers:
    - peer0.org2.example.com
    - peer1.org2.example.com
    certificateAuthorities:
    - ca.org2.example.com
peers:
  peer0.org2.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf2gAwIBAgIQU4hPthwz91ncEHRSu0EwpjAKBggqhkjOPQQDAjB2MQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
        Y2Eub3JnMi5leGFtcGxlLmNvbTAeFw0yMDA0MTIwNDA1MDBaFw0zMDA0MTAwNDA1
        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMR8wHQYD
        VQQDExZ0bHNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
        AQcDQgAExoqdrP4xlblRMdCppih7vIwsUl+Rmkenva8XaMphn4VglgTtbDd0gRkG
        5k87TddnfbmSjWBfDmpK4weBNqI2caNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
        DgQiBCB0EVyV6BUon9rvUYEAeeCDhqp5SeTTIdCOCARv9nMbljAKBggqhkjOPQQD
        AgNJADBGAiEAz1VJgBZLjEPXnIcA1P+OmgNgZvV00Kb+2H/uxqFJeWkCIQCW4IMS
        UopQ8oJrD5lYGwCmkRAY6OPFKBO5gN3ZjrqTZw==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      hostnameOverride: peer0.org2.example.com
  peer1.org2.example.com:
    url: grpcs://localhost:10051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf2gAwIBAgIQU4hPthwz91ncEHRSu0EwpjAKBggqhkjOPQQDAjB2MQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
        Y2Eub3JnMi5leGFtcGxlLmNvbTAeFw0yMDA0MTIwNDA1MDBaFw0zMDA0MTAwNDA1
        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMR8wHQYD
        VQQDExZ0bHNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
        AQcDQgAExoqdrP4xlblRMdCppih7vIwsUl+Rmkenva8XaMphn4VglgTtbDd0gRkG
        5k87TddnfbmSjWBfDmpK4weBNqI2caNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
        DgQiBCB0EVyV6BUon9rvUYEAeeCDhqp5SeTTIdCOCARv9nMbljAKBggqhkjOPQQD
        AgNJADBGAiEAz1VJgBZLjEPXnIcA1P+OmgNgZvV00Kb+2H/uxqFJeWkCIQCW4IMS
        UopQ8oJrD5lYGwCmkRAY6OPFKBO5gN3ZjrqTZw==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.org2.example.com
      hostnameOverride: peer1.org2.example.com
certificateAuthorities:
  ca.org2.example.com:
    url: https://localhost:8054
    caName: ca-org2
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICUTCCAfegAwIBAgIQLDJFktYEqLpoxAlCJMHaVzAKBggqhkjOPQQDAjBzMQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
        b3JnMi5leGFtcGxlLmNvbTAeFw0yMDA0MTIwNDA1MDBaFw0zMDA0MTAwNDA1MDBa
        MHMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
        YW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMRwwGgYDVQQD
        ExNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
        T/13mtj1feBtPoJ1+IrAhiSIqQXNhzC4aJuxYP7shD2XNdVP8XYiZRHSb2xHjZOy
        Xsjb11To3CVWzdT4/h39jqNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQG
        CCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCBQ
        QLsh2jPBRu9D+94gsV1x9n4Qre/ymV/HEAr411G2kzAKBggqhkjOPQQDAgNIADBF
        AiA0bC2aHrzJW8YZQenDc224CrEqxMGs0fFTL/Cn4kmm0AIhAOOePVdxlqNlPy0C
        xNUkp4QC6/zJaHGc8axWTX8nYBQX
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
