certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVzCCAf2gAwIBAgIQWssalJrrMXy17LV+avWJDDAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA2MTgwODM5MDBaFw0zMDA2MTYwODM5

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEQIVvFUvPULYX3ZVBQWPGGGvq5ib9PFAQOXQ5FMIanTpeBHr7adpX9RK1

        vqAGgMpZvwt8Ca48XUoOARDFc7XbSaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCDZeodMfgWIrRuXhO9LH4NTpEoGRNE6yjkbrV/sWM3I5TAKBggqhkjOPQQD

        AgNIADBFAiEA/RF7OEXT44xxUjrtm45TIiwJilod8ixJIU9wtgRohxgCIG+tEgMB

        Gbz8ujEyBnOBKocjehr7NYRUk6jYVmCYEHMr

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVzCCAf2gAwIBAgIQWssalJrrMXy17LV+avWJDDAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA2MTgwODM5MDBaFw0zMDA2MTYwODM5

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEQIVvFUvPULYX3ZVBQWPGGGvq5ib9PFAQOXQ5FMIanTpeBHr7adpX9RK1

        vqAGgMpZvwt8Ca48XUoOARDFc7XbSaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCDZeodMfgWIrRuXhO9LH4NTpEoGRNE6yjkbrV/sWM3I5TAKBggqhkjOPQQD

        AgNIADBFAiEA/RF7OEXT44xxUjrtm45TIiwJilod8ixJIU9wtgRohxgCIG+tEgMB

        Gbz8ujEyBnOBKocjehr7NYRUk6jYVmCYEHMr

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
