certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVjCCAf2gAwIBAgIQD0fd2LPIKDuu3I0LLKQbyzAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA3MDkxNDE5MDBaFw0zMDA3MDcxNDE5

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEuDzcHtAbqGO2ZuhN2I8ieJWCWcGUiqmNhxim/Oclod2MmIDfwPvZ+Xs+

        Ejeh6qIbVbz3+1e3jAHp3DmJZWweVKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCC8iWkIeQKBUOJD832H5TuiC9IlA6kXnBg1oRKkRxj9PDAKBggqhkjOPQQD

        AgNHADBEAiBSn+FuaVl/k4gZDv8AxOEin/6/RhEy0Wj5QeOvTa2IdwIgXmY+VHn5

        ODONwYQWHM7wpyTOH5rwosXN+VZBgHP3mZA=

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVjCCAf2gAwIBAgIQD0fd2LPIKDuu3I0LLKQbyzAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA3MDkxNDE5MDBaFw0zMDA3MDcxNDE5

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEuDzcHtAbqGO2ZuhN2I8ieJWCWcGUiqmNhxim/Oclod2MmIDfwPvZ+Xs+

        Ejeh6qIbVbz3+1e3jAHp3DmJZWweVKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCC8iWkIeQKBUOJD832H5TuiC9IlA6kXnBg1oRKkRxj9PDAKBggqhkjOPQQD

        AgNHADBEAiBSn+FuaVl/k4gZDv8AxOEin/6/RhEy0Wj5QeOvTa2IdwIgXmY+VHn5

        ODONwYQWHM7wpyTOH5rwosXN+VZBgHP3mZA=

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
