certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVjCCAf2gAwIBAgIQHTOWbsWYlBqQSYPC6H87ADAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA3MTEwOTE1MDBaFw0zMDA3MDkwOTE1

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEe8r9kj0qNoeFIrbOgsJ0xJMLB+HGCKyhXP4MsBe2eI0Ejkled9SUi4GW

        Wz/TyRHn6QPXO5Qgr9KdO+wmRcwoZKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCAq0Pp1lKPBnqz3Z5ooyGU7Lb2eUPiKfjGxaihVsQ+LcTAKBggqhkjOPQQD

        AgNHADBEAiBs69Y5/JxS7Wu0qSxxmn7BUK6pue+T+gPVpw2bD8hynQIgNNQ5X2NO

        oYeXK9wDDnlHYkAdtBYFEXo3Bj/TpQUAF9c=

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVjCCAf2gAwIBAgIQHTOWbsWYlBqQSYPC6H87ADAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA3MTEwOTE1MDBaFw0zMDA3MDkwOTE1

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEe8r9kj0qNoeFIrbOgsJ0xJMLB+HGCKyhXP4MsBe2eI0Ejkled9SUi4GW

        Wz/TyRHn6QPXO5Qgr9KdO+wmRcwoZKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCAq0Pp1lKPBnqz3Z5ooyGU7Lb2eUPiKfjGxaihVsQ+LcTAKBggqhkjOPQQD

        AgNHADBEAiBs69Y5/JxS7Wu0qSxxmn7BUK6pue+T+gPVpw2bD8hynQIgNNQ5X2NO

        oYeXK9wDDnlHYkAdtBYFEXo3Bj/TpQUAF9c=

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
