certificateAuthorities:
  ca.org1.example.com:
    caName: ca.org1.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWTCCAf6gAwIBAgIRAMJ10xgE1JcZoPhLsFwo7s0wCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjAwNzEyMTI0OTAwWhcNMzAwNzEwMTI0

        OTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABJJ0/uHfiYOKAweaOwJLVIFHth2TFmxrRj987J5TmFuQ07RqgKjX6rER

        7HubDy56LaMI3BS00m6McCyVhYrLokSjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgifdTxdfO0RpDjMchVhqbNb16q2eE5tQwgKO7DejBJPowCgYIKoZIzj0E

        AwIDSQAwRgIhAIo74qhuUDSx+RvFsGea5wOBzIDJndhmikZOR/ZMwuCrAiEAod5f

        hnn5Kmrr6JmwU7PPyX1O+QOgjm2CRGDoTtwxwKo=

        -----END CERTIFICATE-----

        '}
    url: https://localhost:7054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org1
name: first-network-org1
organizations:
  Org1:
    certificateAuthorities: [ca.org1.example.com]
    mspid: Org1MSP
    peers: [peer0.org1.example.com]
peers:
  peer0.org1.example.com:
    grpcOptions: {hostnameOverride: peer0.org1.example.com, ssl-target-name-override: peer0.org1.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWTCCAf6gAwIBAgIRAMJ10xgE1JcZoPhLsFwo7s0wCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjAwNzEyMTI0OTAwWhcNMzAwNzEwMTI0

        OTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABJJ0/uHfiYOKAweaOwJLVIFHth2TFmxrRj987J5TmFuQ07RqgKjX6rER

        7HubDy56LaMI3BS00m6McCyVhYrLokSjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgifdTxdfO0RpDjMchVhqbNb16q2eE5tQwgKO7DejBJPowCgYIKoZIzj0E

        AwIDSQAwRgIhAIo74qhuUDSx+RvFsGea5wOBzIDJndhmikZOR/ZMwuCrAiEAod5f

        hnn5Kmrr6JmwU7PPyX1O+QOgjm2CRGDoTtwxwKo=

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:7051
version: 1.0.0
