certificateAuthorities:
  ca.org2.example.com:
    caName: ca.org2.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf2gAwIBAgIQBMALMPWFQTZcVGgwyklyMjAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMi5leGFtcGxlLmNvbTAeFw0yMDA3MTIxMzA5MDBaFw0zMDA3MTAxMzA5

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEmTSj3MtRgvn2WYuiWsxa/HkANyEd3NbL99b2mxwKqbFv5mTqt/fg7GuY

        oeTwg8dcTjxk7XgfiLoX8xzKXVX1mKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCAg5hA8oBWcztrcqzruwDNu/7o5hnniFC7KODS8bPokizAKBggqhkjOPQQD

        AgNJADBGAiEAretthbciKN5X0Ad+tmc+IhRwJCxME2gAOQg7UzSmyDICIQDFEWI8

        5K+hP6+bhCD+lR3wOTSFY8oIWgTFYuBuKF/pZw==

        -----END CERTIFICATE-----

        '}
    url: https://localhost:8054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org2
name: first-network-org2
organizations:
  Org2:
    certificateAuthorities: [ca.org2.example.com]
    mspid: Org2MSP
    peers: [peer0.org2.example.com]
peers:
  peer0.org2.example.com:
    grpcOptions: {hostnameOverride: peer0.org2.example.com, ssl-target-name-override: peer0.org2.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf2gAwIBAgIQBMALMPWFQTZcVGgwyklyMjAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMi5leGFtcGxlLmNvbTAeFw0yMDA3MTIxMzA5MDBaFw0zMDA3MTAxMzA5

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcyLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmcyLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEmTSj3MtRgvn2WYuiWsxa/HkANyEd3NbL99b2mxwKqbFv5mTqt/fg7GuY

        oeTwg8dcTjxk7XgfiLoX8xzKXVX1mKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCAg5hA8oBWcztrcqzruwDNu/7o5hnniFC7KODS8bPokizAKBggqhkjOPQQD

        AgNJADBGAiEAretthbciKN5X0Ad+tmc+IhRwJCxME2gAOQg7UzSmyDICIQDFEWI8

        5K+hP6+bhCD+lR3wOTSFY8oIWgTFYuBuKF/pZw==

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:8051
version: 1.0.0
