certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf6gAwIBAgIRAPrUFURBy3OYcfEsoCwnHWgwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNzEyMTMzNTAwWhcNMzAwNzEwMTMz

        NTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABKyTKbP+o04wZOR/XGjM7C5iT0dosANh1twRkCyCj0Mda/hzGQaLdATo

        JKjHBzwaEEjFdIIrUrZNiIQM7+IZu7GjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgiLEgfzaYEhh4bPexqXAnHo+geQ85jvagm2dmKIv1FIkwCgYIKoZIzj0E

        AwIDSAAwRQIhAKjWfATI26okmHyKjoZLD7Kb+fLimyCjwoqkZ5xTPyMqAiAPW4xX

        BOEalLqHMPYkoobRuD4+kZf4qgroZujJj8T6iw==

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf6gAwIBAgIRAPrUFURBy3OYcfEsoCwnHWgwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNzEyMTMzNTAwWhcNMzAwNzEwMTMz

        NTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABKyTKbP+o04wZOR/XGjM7C5iT0dosANh1twRkCyCj0Mda/hzGQaLdATo

        JKjHBzwaEEjFdIIrUrZNiIQM7+IZu7GjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgiLEgfzaYEhh4bPexqXAnHo+geQ85jvagm2dmKIv1FIkwCgYIKoZIzj0E

        AwIDSAAwRQIhAKjWfATI26okmHyKjoZLD7Kb+fLimyCjwoqkZ5xTPyMqAiAPW4xX

        BOEalLqHMPYkoobRuD4+kZf4qgroZujJj8T6iw==

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
