certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf6gAwIBAgIRAOuHgaUXIXdi95wyYxkaq1wwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNjExMTIwNzAwWhcNMzAwNjA5MTIw

        NzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABFJoQ1CutiJAEf5/PgQAVMQg+9KRB1pHDlChakXdYDsPmyyjK95OK+yc

        CiivYqZREZiIRoVdzzXrI5OqJ/4AAuajbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgJjqSJyU0/SMOaqgPPrxaqU6VY5FX8/fstnEMJrd1MygwCgYIKoZIzj0E

        AwIDSAAwRQIgRrHn/8bhxIowrvvVva3w/Pq4I7vN7Pb+yfJ60v1fOnECIQCvaSR8

        GdRNgR5DndXMLKnaU1G6WlIbfCqw4sAv82s64A==

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf6gAwIBAgIRAOuHgaUXIXdi95wyYxkaq1wwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNjExMTIwNzAwWhcNMzAwNjA5MTIw

        NzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABFJoQ1CutiJAEf5/PgQAVMQg+9KRB1pHDlChakXdYDsPmyyjK95OK+yc

        CiivYqZREZiIRoVdzzXrI5OqJ/4AAuajbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgJjqSJyU0/SMOaqgPPrxaqU6VY5FX8/fstnEMJrd1MygwCgYIKoZIzj0E

        AwIDSAAwRQIgRrHn/8bhxIowrvvVva3w/Pq4I7vN7Pb+yfJ60v1fOnECIQCvaSR8

        GdRNgR5DndXMLKnaU1G6WlIbfCqw4sAv82s64A==

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
