certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVzCCAf6gAwIBAgIRAIYF1WZDguuzp0QgHFAgI5YwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNjMwMTQ0MzAwWhcNMzAwNjI4MTQ0

        MzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABPAlXRblrRcPzqHJysyKKqxP9s4DQi+2Hi/B4OO5wLZvdvCH5zNeEkOy

        29IJAknMMr58f8q5zgql5Fiz7tVTIWGjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgAto42oAtDOGPqWjBCWdtGbiJHSn8Lp0KGrIilD8flOUwCgYIKoZIzj0E

        AwIDRwAwRAIgcrizzliwsjB9d8PAst0Ci5uD/e4s5K3irBrT+ePjehwCIH82FGgJ

        2SgSgowbYAL/PMiPFoN8uX4s2uEBLl3dvPR+

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVzCCAf6gAwIBAgIRAIYF1WZDguuzp0QgHFAgI5YwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNjMwMTQ0MzAwWhcNMzAwNjI4MTQ0

        MzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABPAlXRblrRcPzqHJysyKKqxP9s4DQi+2Hi/B4OO5wLZvdvCH5zNeEkOy

        29IJAknMMr58f8q5zgql5Fiz7tVTIWGjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgAto42oAtDOGPqWjBCWdtGbiJHSn8Lp0KGrIilD8flOUwCgYIKoZIzj0E

        AwIDRwAwRAIgcrizzliwsjB9d8PAst0Ci5uD/e4s5K3irBrT+ePjehwCIH82FGgJ

        2SgSgowbYAL/PMiPFoN8uX4s2uEBLl3dvPR+

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
