certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf6gAwIBAgIRALX9NKm2ZEUOANzeVjcqUFQwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNzEyMTI0OTAwWhcNMzAwNzEwMTI0

        OTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABKfdIY+H4gGz8NDwxtGLaAT6aPL4u3unweU0Dq8/o7S+Lg+QTNEaBZU5

        cQ56GEXzHZZlupD62/USQyE2K0DrV2CjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgEuHsGt1xnPOSVN3wEQY5Li+Rc1l6QdlfTX/QcAQ00j8wCgYIKoZIzj0E

        AwIDSAAwRQIgfSLkwRC9PKe20FzEogbiaShsIZzpMXdsovhRC2MhPs4CIQD+pEZH

        vx2XX27PbmQr4uYvyP11sTS17nVZJWQ/mYbc9g==

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf6gAwIBAgIRALX9NKm2ZEUOANzeVjcqUFQwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNzEyMTI0OTAwWhcNMzAwNzEwMTI0

        OTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABKfdIY+H4gGz8NDwxtGLaAT6aPL4u3unweU0Dq8/o7S+Lg+QTNEaBZU5

        cQ56GEXzHZZlupD62/USQyE2K0DrV2CjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgEuHsGt1xnPOSVN3wEQY5Li+Rc1l6QdlfTX/QcAQ00j8wCgYIKoZIzj0E

        AwIDSAAwRQIgfSLkwRC9PKe20FzEogbiaShsIZzpMXdsovhRC2MhPs4CIQD+pEZH

        vx2XX27PbmQr4uYvyP11sTS17nVZJWQ/mYbc9g==

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
