---
name: first-network-org3
version: 1.0.0
client:
  organization: Org3
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org3:
    mspid: Org3MSP
    peers:
    - peer0.org3.example.com
    certificateAuthorities:
    - ca.org3.example.com
peers:
  peer0.org3.example.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAJDxG9MvOf7RjijlcVB8iR8wCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNTI5MTgxNTAwWhcNMzAwNTI3MTgx
        NTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G
        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABEGao2l/eDAWfKG0S2CIC2EfZ3m0Z3yeU0q3ENm6nXs9XRRr/gnUO2pA
        JqI3KWkDFRyhT+yqPFzFzPJKExDO3TOjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgnjynlUAw4oDmwAL7pQ5W0+w6c6xwZTnHwdcQmOzm6UcwCgYIKoZIzj0E
        AwIDSAAwRQIhAIFE2YyvfJD/Cn2QXScWayCqXbmfJGAKCuxl7iTV9fp3AiAN5Bqv
        H0bPPCZSx9/I3OJHotipGtDBXczEOnnp4kNXmA==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.org3.example.com
      hostnameOverride: peer0.org3.example.com

certificateAuthorities:
  ca.org3.example.com:
    url: https://localhost:9054
    caName: ca.org3.example.com
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAJDxG9MvOf7RjijlcVB8iR8wCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNTI5MTgxNTAwWhcNMzAwNTI3MTgx
        NTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G
        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABEGao2l/eDAWfKG0S2CIC2EfZ3m0Z3yeU0q3ENm6nXs9XRRr/gnUO2pA
        JqI3KWkDFRyhT+yqPFzFzPJKExDO3TOjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgnjynlUAw4oDmwAL7pQ5W0+w6c6xwZTnHwdcQmOzm6UcwCgYIKoZIzj0E
        AwIDSAAwRQIhAIFE2YyvfJD/Cn2QXScWayCqXbmfJGAKCuxl7iTV9fp3AiAN5Bqv
        H0bPPCZSx9/I3OJHotipGtDBXczEOnnp4kNXmA==
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
