certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf6gAwIBAgIRAOYD4B40pNAo2zZ/LzzL4wowCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNjI1MTQwNzAwWhcNMzAwNjIzMTQw

        NzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABLpmgoASJ1vt95zbip0E2nJCE5HKfd/RtCPYd1ZjKIxuRVIDEoYj+nTK

        6wfhVz5ckvT+KEfSqDVW4cfobFBvlwGjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgvsMjljmypRSDxwkFRDDp5IRg8Vasaou0+sfZroFfhIAwCgYIKoZIzj0E

        AwIDSAAwRQIgZ1M0ceEXvutM3m9+iqlAS6ZtbmvzqyqScP0xEIBu5z4CIQDgjTu2

        TxpUSPUBiZV9Km9VlVrTTb5FmTI9jFnpSKmU3g==

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWDCCAf6gAwIBAgIRAOYD4B40pNAo2zZ/LzzL4wowCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNjI1MTQwNzAwWhcNMzAwNjIzMTQw

        NzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABLpmgoASJ1vt95zbip0E2nJCE5HKfd/RtCPYd1ZjKIxuRVIDEoYj+nTK

        6wfhVz5ckvT+KEfSqDVW4cfobFBvlwGjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgvsMjljmypRSDxwkFRDDp5IRg8Vasaou0+sfZroFfhIAwCgYIKoZIzj0E

        AwIDSAAwRQIgZ1M0ceEXvutM3m9+iqlAS6ZtbmvzqyqScP0xEIBu5z4CIQDgjTu2

        TxpUSPUBiZV9Km9VlVrTTb5FmTI9jFnpSKmU3g==

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
