---
name: first-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAMUJAgMJH4xYH+PejS1iY4gwCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
        c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjAwNTI5MTgxNTAwWhcNMzAwNTI3MTgx
        NTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G
        A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABAqj8AXxoattXwoum2qK5Su23ZrcR9wSRg7V60ZdmETQ0COFM1dIG5J/
        ozkUyMd+KS4lPH+Kx8ymy0YQpGw9qk6jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgfwyYGtDasTYn2f2VvNpafxcc9SUSWmWbOLdJ3dS0ZgIwCgYIKoZIzj0E
        AwIDSAAwRQIgZTg6KzbN3OC0nrAeOCWiLQqYDkwO5uoHh0mLBy9zgGQCIQD/AQ1j
        nciJPfumqNwWoEyo6TE8KuL9NNCGhykGjSspHA==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com

certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca.org1.example.com
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAMUJAgMJH4xYH+PejS1iY4gwCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs
        c2NhLm9yZzEuZXhhbXBsZS5jb20wHhcNMjAwNTI5MTgxNTAwWhcNMzAwNTI3MTgx
        NTAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0G
        A1UEAxMWdGxzY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABAqj8AXxoattXwoum2qK5Su23ZrcR9wSRg7V60ZdmETQ0COFM1dIG5J/
        ozkUyMd+KS4lPH+Kx8ymy0YQpGw9qk6jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgfwyYGtDasTYn2f2VvNpafxcc9SUSWmWbOLdJ3dS0ZgIwCgYIKoZIzj0E
        AwIDSAAwRQIgZTg6KzbN3OC0nrAeOCWiLQqYDkwO5uoHh0mLBy9zgGQCIQD/AQ1j
        nciJPfumqNwWoEyo6TE8KuL9NNCGhykGjSspHA==
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
