certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVzCCAf2gAwIBAgIQfUG1MYIx2AjC+P/8cfqF2jAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA3MTIxMzA5MDBaFw0zMDA3MTAxMzA5

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAE+Il4m3ZWxcAlevx5a7dGuv4OuSitIv9bHrqVmCt8gNoZfWypqP1nGvRd

        VoBxyfF0L7+QOlrw2qFz6KNoOdNW46NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCAqQ/Oevi20+OaRSpga1e1TxGMwTeJoXHKUue3M6f4vqzAKBggqhkjOPQQD

        AgNIADBFAiEAlwdQ7OVmQdanbyAwP834HvkCXJvDTuj1uBGX0fu/9c8CICldyHVN

        F6ffgSYzJRjL3qq9+Kchgasmo87bh2V9oZ+H

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVzCCAf2gAwIBAgIQfUG1MYIx2AjC+P/8cfqF2jAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMy5leGFtcGxlLmNvbTAeFw0yMDA3MTIxMzA5MDBaFw0zMDA3MTAxMzA5

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmczLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmczLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAE+Il4m3ZWxcAlevx5a7dGuv4OuSitIv9bHrqVmCt8gNoZfWypqP1nGvRd

        VoBxyfF0L7+QOlrw2qFz6KNoOdNW46NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCAqQ/Oevi20+OaRSpga1e1TxGMwTeJoXHKUue3M6f4vqzAKBggqhkjOPQQD

        AgNIADBFAiEAlwdQ7OVmQdanbyAwP834HvkCXJvDTuj1uBGX0fu/9c8CICldyHVN

        F6ffgSYzJRjL3qq9+Kchgasmo87bh2V9oZ+H

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
