certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWTCCAf6gAwIBAgIRANkkzxHNh51CWqILzxZWr8QwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNjI0MDgwNjAwWhcNMzAwNjIyMDgw

        NjAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABKqE5VnVGogLl5X4IhnwMU5wfNKq9sj1aC6HgJWHhcr64zaUEdTzxUTK

        Kfxct+gfQ9CSvB2H6pDfcmGt9DNYUVajbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgfHGO4A2BKmV9V5NkNp6mN+tUddkTNfU3ogkfyr1UbD0wCgYIKoZIzj0E

        AwIDSQAwRgIhANLklvTD1qeniV32qdphlbiR5gr0VUCb+/3xT1OLJJleAiEAwGfB

        /ZiZFZ2SyQqcSu/kZKDmSeFyfU9bY6vz41jg2xg=

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWTCCAf6gAwIBAgIRANkkzxHNh51CWqILzxZWr8QwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNjI0MDgwNjAwWhcNMzAwNjIyMDgw

        NjAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABKqE5VnVGogLl5X4IhnwMU5wfNKq9sj1aC6HgJWHhcr64zaUEdTzxUTK

        Kfxct+gfQ9CSvB2H6pDfcmGt9DNYUVajbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQgfHGO4A2BKmV9V5NkNp6mN+tUddkTNfU3ogkfyr1UbD0wCgYIKoZIzj0E

        AwIDSQAwRgIhANLklvTD1qeniV32qdphlbiR5gr0VUCb+/3xT1OLJJleAiEAwGfB

        /ZiZFZ2SyQqcSu/kZKDmSeFyfU9bY6vz41jg2xg=

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
