certificateAuthorities:
  ca.org1.example.com:
    caName: ca.org1.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVjCCAf2gAwIBAgIQYmsPlseNI9p1VdLCj/1//jAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yMDA3MTExMTAzMDBaFw0zMDA3MDkxMTAz

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEOzwqIdWzr0UAMKXkvqNRFX9mwd3NMkk3zMg+TkJ00clqJqOppOB0MQs7

        VZPscwm0PIINpQMXHvapjqVfaui9X6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCBuPBMwdtNosOHkBzxS3AEBzRQRy5AjG2vchJ6bKX6t2TAKBggqhkjOPQQD

        AgNHADBEAiAcUfHJkqABVzOSrMbzKyRXoYYP+mKb9tFA81LOn/btBAIgcrlJvhO6

        wqmt/1pWPgwvdwogy+jVYCBJ/vBNo3LqSpQ=

        -----END CERTIFICATE-----

        '}
    url: https://localhost:7054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org1
name: first-network-org1
organizations:
  Org1:
    certificateAuthorities: [ca.org1.example.com]
    mspid: Org1MSP
    peers: [peer0.org1.example.com]
peers:
  peer0.org1.example.com:
    grpcOptions: {hostnameOverride: peer0.org1.example.com, ssl-target-name-override: peer0.org1.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICVjCCAf2gAwIBAgIQYmsPlseNI9p1VdLCj/1//jAKBggqhkjOPQQDAjB2MQsw

        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy

        YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz

        Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yMDA3MTExMTAzMDBaFw0zMDA3MDkxMTAz

        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH

        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD

        VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D

        AQcDQgAEOzwqIdWzr0UAMKXkvqNRFX9mwd3NMkk3zMg+TkJ00clqJqOppOB0MQs7

        VZPscwm0PIINpQMXHvapjqVfaui9X6NtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud

        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud

        DgQiBCBuPBMwdtNosOHkBzxS3AEBzRQRy5AjG2vchJ6bKX6t2TAKBggqhkjOPQQD

        AgNHADBEAiAcUfHJkqABVzOSrMbzKyRXoYYP+mKb9tFA81LOn/btBAIgcrlJvhO6

        wqmt/1pWPgwvdwogy+jVYCBJ/vBNo3LqSpQ=

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:7051
version: 1.0.0
