certificateAuthorities:
  ca.org3.example.com:
    caName: ca.org3.example.com
    httpOptions: {verify: false}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWTCCAf6gAwIBAgIRALpUiA1eTy1oJOT9WYM5dPgwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNjEyMDgxMDAwWhcNMzAwNjEwMDgx

        MDAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABFtrukqk9pJ/oOP2DqLPVhxLwi4Kh+NxV3mNt4qD6Ob2JeCK0MHRj3wI

        LcMIl6Gq7Bxuvfb5adsUgGMa2kaFKn2jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQg1p23dBiQi2+JD+T2ey8+vIrkPthqhuWkX5cy44VNzNYwCgYIKoZIzj0E

        AwIDSQAwRgIhANLR7BX8vRyM78q3VBNQhJ9LoVLCtDR/4uSg5lT5TqMHAiEAjSew

        VIc76OxKiRvqUpkT6Uls0Us4fWG1cEId+2SBMAs=

        -----END CERTIFICATE-----

        '}
    url: https://localhost:9054
client:
  connection:
    timeout:
      peer: {endorser: '300'}
  organization: Org3
name: first-network-org3
organizations:
  Org3:
    certificateAuthorities: [ca.org3.example.com]
    mspid: Org3MSP
    peers: [peer0.org3.example.com]
peers:
  peer0.org3.example.com:
    grpcOptions: {hostnameOverride: peer0.org3.example.com, ssl-target-name-override: peer0.org3.example.com}
    tlsCACerts: {pem: '-----BEGIN CERTIFICATE-----

        MIICWTCCAf6gAwIBAgIRALpUiA1eTy1oJOT9WYM5dPgwCgYIKoZIzj0EAwIwdjEL

        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG

        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzMuZXhhbXBsZS5jb20xHzAdBgNVBAMTFnRs

        c2NhLm9yZzMuZXhhbXBsZS5jb20wHhcNMjAwNjEyMDgxMDAwWhcNMzAwNjEwMDgx

        MDAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE

        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMy5leGFtcGxlLmNvbTEfMB0G

        A1UEAxMWdGxzY2Eub3JnMy5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49

        AwEHA0IABFtrukqk9pJ/oOP2DqLPVhxLwi4Kh+NxV3mNt4qD6Ob2JeCK0MHRj3wI

        LcMIl6Gq7Bxuvfb5adsUgGMa2kaFKn2jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV

        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV

        HQ4EIgQg1p23dBiQi2+JD+T2ey8+vIrkPthqhuWkX5cy44VNzNYwCgYIKoZIzj0E

        AwIDSQAwRgIhANLR7BX8vRyM78q3VBNQhJ9LoVLCtDR/4uSg5lT5TqMHAiEAjSew

        VIc76OxKiRvqUpkT6Uls0Us4fWG1cEId+2SBMAs=

        -----END CERTIFICATE-----

        '}
    url: grpcs://localhost:9051
version: 1.0.0
